# Generated by Django 3.0.8 on 2020-07-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='released',
            field=models.DateField(blank=True, null=True),
        ),
    ]
